import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full flex justify-center items-center py-4 border-b border-gray-200 dark:border-gray-700 mb-8">
          <div className="flex gap-6">
            <Link href="/" className="font-semibold text-base hover:underline">Home</Link>
            <Link href="/blog" className="font-semibold text-base hover:underline">Blog</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
